### ISSUE TITLE
支持一下这个框架，顺便提几个建议

### ISSUE THREAD

**Issue by hzqst** [topcpporg/rest_rpc#7]
1、同步客户端可以加入超时设置（主要是我不太想随便改第三方库的代码，但是为了支持超时只能先改为敬了。
2、pub sub功能只支持传递一个参数吗？每次传N个参数都要封装一个struct很麻烦啊，如果可以一次传多个参数就好了。
2、可以加入ssl支持（可选）并且把设置ssl参数的接口暴露给开发者，这样可以自建证书做双向认证，提高数据传输安全性。

**Comment by qicosmos** [comment]
@hzqst pub sub是支持多个参数的。
谢谢你的建议，我们会考虑的。
我们也欢迎你提交ssl相关pr。

**Comment by abbycin** [comment]
我也提一点意见。 一直想好好看一下源码， 但是源码都是单个都文件，这就算了，某个有文件里面用到的类型又没有声明，而是放在别的头文件里面，包含头文件的时候还得特别注意顺序。 问题就是，看源码的过程中发现一个类型，想看看到底是什么都没有办法（我用的CLion），只能grep查找。等找到了，又忘记了之前的东西。。

**Comment by Madokakaroto** [comment]
@abbycin  你好，感谢你来提建议。不过Clion打开CMakeLists.txt所在的目录是可以正确parse里面的符号信息的，不会影响源代码的阅读。头文件不包含其他头文件，而用编译单元包含所需的头文件也是boost常用的头文件管理方式；头文件互相包含也会影响工程性和拖慢有很多编译单元工程的编译速度，我们也是推荐使用编译单元来组织头文件，而头文件尽量使用前向申明。
